### ISSUE TITLE
How to add a support for EEPROM PUYA P25D21H

### ISSUE THREAD

**Issue by tomasjura** [markusj/upd72020x-load#10]
Hi I'm trying to add support for EEPROM chip PUYA P25D21H. Here is output of the eeprom read

```
./upd72020x-load -r -b 0x05 -d 0x00 -f 0x0 -o fw_orig
Doing the reading
bus = 5 
dev = 0 
fct = 0 
fname = fw_orig 
Found an UPD720202 chipset
got firmware version: 201107
EEPROM installed
got rom_info: 854012
got rom_config: 0
unknown EEPROM, no parameters found
```
0x854012 is not under supported chips in the function `lookup_rompar`

Opening the box I found that my EEPROM is PUYA chip P25D21H. Some info about that chip (data sheet, SFDP info) is [here](https://www.gitmemory.com/issue/flashrom/flashrom/153/662003976).

How to add the support for the mentioned EEPROM? 

I guess that adding a proper line into `lookup_rompar` should be sufficient.  Though have read your blogs about , I haven't find how to derive the magic address returning from `lookup_rompar`.

I also tried to upload firmware into memory using `-u` command, but
it fails. My conjecture is that the fw upload to the memory is not
dependent to EEPROM type. Is the upload to firmware memory dependent
to EEPROM type? Can be detection of EEPROM skiped for `-u` upload? Or
the memory upload is somewhat dependent on EEPROM type?

For the sake of completeness here is a hexdump from pci device configuration `cat /sys/bus/pci/devices/0000:05:00.0/config| od -t a`
```
0000000 12 19 15 00 06 04 10 00 02 30 03 0c 10 00 00 00
0000020 04 00 80 f4 00 00 00 00 00 00 00 00 00 00 00 00
0000040 00 00 00 00 00 00 00 00 00 00 00 00 ff ff ff ff
0000060 00 00 00 00 50 00 00 00 00 00 00 00 00 01 00 00
0000100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000120 01 70 c3 c9 08 00 00 00 00 00 00 00 00 00 00 00
0000140 30 20 00 00 00 00 00 00 00 00 00 00 07 11 20 00
0000160 05 90 86 00 00 00 00 00 00 00 00 00 00 00 00 00
0000200 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000220 11 a0 07 80 00 10 00 00 80 10 00 00 00 00 00 00
0000240 10 00 02 00 c0 8f 00 00 00 28 11 00 12 ec 07 00
0000260 40 00 11 10 00 00 00 00 00 00 00 00 00 00 00 00
0000300 00 00 00 00 10 08 00 00 00 00 00 00 00 00 00 00
0000320 02 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
0000340 00 00 00 00 00 00 05 00 00 00 01 05 12 40 85 00
0000360 00 00 00 00 00 00 00 80 00 00 00 00 00 00 00 00
0000400 01 00 01 15 00 00 00 00 00 00 00 00 30 20 06 00
0000420 00 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00
0000440 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000500 03 00 01 15 ff ff ff ff ff ff ff ff 00 00 00 00
0000520 18 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
0000540 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0010000
```

Thanks ahead for an answer
Tomas

**Comment by markusj** [comment]
Hello Thomas,

I took those magic numbers from page 119 of the datasheet by Renesas (ISG-NK1-110027 Rev.2.00). I do not know how they are derived and thus I am reluctant to make any experiments with them.

But: Using the `-u` option should work now, there was a check at the wrong place which bailed out unnecessarily.
