### ISSUE TITLE
VendorID Error 

### ISSUE THREAD

**Issue by Ramlord** [markusj/upd72020x-load#11]
I'm on X370 and Arch Linux and ran the command but got this error, I've been having issues with that card as a whole though so my chipset may be the issue 
![image](https://user-images.githubusercontent.com/42529354/97234622-716a5e00-179e-11eb-9f41-6a426e5c4b8b.png)

**Comment by markusj** [comment]
You must specify the correct PCI bus, device and function addresses. The readme file just provides an example, those addresses are different depending on your hardware setup. According to your lspci output (see very first column for addresses), you should try using `-b 0x0c` instead `-b 0x02`.
