### ISSUE TITLE
Check firmware version currently in card/ROM

### ISSUE THREAD

**Issue by meetnick** [markusj/upd72020x-load#21]
First of all, Thank you so much for this tool. This is amazing and helpful for those who "loves" (sarcasm) Renesas USB expansion PCIE card.

I'm wondering if is there any way to fetch firmware version shipped on this board. In order to make sure this is running on desired/latest version.

**Comment by markusj** [comment]
The tool should print the active firmware version when you start it (https://github.com/markusj/upd72020x-load/blob/c72ae091d8009dfc4955be53cbaf7f19c6c16d2f/upd72020x-load.c#L668). Without implementing any feature that decodes the ROM (which is also possible, see #15), you can fully power-cycle your computer (unplug power, press power button, plug power in again) and then observe the output.
