### ISSUE TITLE
Is checking firmware by providing a file to compare going to be implemented?

### ISSUE THREAD

**Issue by AreYouLoco** [markusj/upd72020x-load#5]
https://github.com/markusj/upd72020x-load/blob/338a3845fd0e1c29e614f53c464cd701825614a7/upd72020x-load.c#L471

Just an idea or accual implementation plan?

**Comment by markusj** [comment]
Its neither. This is a leftover from the original code which was posted by someone else below [this](http://billauer.co.il/blog/2015/11/renesas-rom-setpci/) blogpost. My focus was on "making things work", not so much on the diagnostics part, which is therefore largely untested and may be buggy.

If you are interested in this feature, feel free to submit a PR. Until then, I will close this issue.
