### ISSUE TITLE
ERROR: SET_DATAx never go to zero

### ISSUE THREAD

**Issue by JulianGro** [markusj/upd72020x-load#7]
Hello,

trying this tool on my uPD720202 controller fails. According to the checksums I am using the same firmware as the person that wrote the README.md

```
motofckr9k@motofckr9k-mint-desktop:~/Schreibtisch/K2026FWUP1$ sudo ./upd72020x-load/upd72020x-load -u -b 0x19 -d 0x00 -f 0x0 -i UPDATE.mem 
Doing the upload
bus = 19 
dev = 0 
fct = 0 
fname = UPDATE.mem 
got firmware version: 202609
EEPROM installed
got rom_info: c22210
got rom_config: 500
setting rom_config: 500
STATUS: enabling firmware upload
STATUS: performing firmware upload
ERROR: SET_DATAx never go to zero
 ======> FAILED
motofckr9k@motofckr9k-mint-desktop:~/Schreibtisch/K2026FWUP1$
```

Absolutelty no idea what this error message could mean.

**Comment by markusj** [comment]
This error message says that the card did not respond as expected. Normally, after enabling the firmware upload, there are two bits which are reset to zero when the chipset is ready. One then can upload the firmware by writing the data alternating into two registers. After writing one word into a register, the corresponding bit must be set to signal the chipset that it should move the word into its internal memory. After processing the word, the chipset then resets this bit.

The code is waiting for the bit to become reset for some time and gives up if the chipset does not respond as expected, this is what happens for you. However, I can not tell why this is happening in your case ...

**Comment by markusj** [comment]
OK, I stand corrected. Currently I see the same error when I recompile the tool. I am still investigating yet.

**Comment by markusj** [comment]
The issue should be fixed as of commit 6f5be4ed98fbc4739ffeb6c518358fd762025ba9. Can you confirm please, @jug007 ?

To be honest, I can not really tell why the upload process worked previously and failed afterwards. The upload process was slightly different than described in the datasheet, but both my old build and the recompiled build did exactly the same, I straced them.

Anyway, now the tool strictly adheres to the procedure described in the datasheet, which is: write DATA0 and DATA1 registers, set signaling bits for both in the control register and then work on DATA0 and DATA1 alternating, with signaling bits set individually. The old code directly started alternating, which turned out to be not reliable ...

Old sequence: Write DATA0, signal DATA0, write DATA1, signal DATA1, repeat (always checking for the signal to be cleared before writing to the registers).
New sequence: Write DATA0 and DATA1, signal both, then continue with old sequence.

**Comment by jug007** [comment]
Hasn't fixed it for me. Still the same error.

**Comment by markusj** [comment]
In this case, I sadly can not do much for you right now. You could try to strace the tool and provide something like the first hundred lines, maybe I can spot some abnormality. But most likely, the chipset just does not respond despite it should ...

**Comment by jug007** [comment]
Guess here it is then: https://gist.github.com/jug007/aadc5135f58415712846b20bf19674cd

**Comment by markusj** [comment]
Did you power off/on your computer since you tried the tool the last time? I just had a brief glimpse on the strace (will take a second look the next days) and it looked like if the firmware upload flag already has been set. If the upload fails at first time, the chipset may be in some undefined state from the uploaders point of view. Turning your computer off and on again resets the chipset such that it behaves again like the uploader expects.

**Comment by jug007** [comment]
Unfortunately it doesn't work, even after rebooting.

**Comment by markusj** [comment]
Hmm, would have been too easy. Can you provide me a strace of the first run after reboot? Maybe I have a chance to at least identify where the upload process gets stuck.

**Comment by jug007** [comment]
Here it is: [log2.txt](https://github.com/markusj/upd72020x-load/files/4681577/log2.txt)

**Comment by markusj** [comment]
Hmm, same pattern. The chipset does not behave as it is supposed to be according to my understanding of the datasheet. You could try to replace `write_bitmask(fd, ctrl_reg, mask, mask)` in line 383 by `write_bit(fd, ctrl_reg, ROM_SET_DATA0, 1)` and add a second call with `write_bit(fd, ctrl_reg, ROM_SET_DATA1, 1)`. But besides that, I do not have any further ideas right now.

**Comment by cranphin** [comment]
Seeing the same issue on my card, investigating.. :)

**Comment by cranphin** [comment]
Also, nice and correct version numbers ;)
```
    uint32_t fw_low = (fw_info >> 8) & 0xff;
    uint32_t fw_high = (fw_info >> 16) & 0xff;

    printf("Current firmware version: %x.%x.%x.%x\n", fw_high / 16, fw_high % 16, fw_low / 16, fw_low % 16);

    int ifile = open(filename, O_RDONLY);
    EXIT_ON_ERR(ifile < 0, "ERROR: cant open file image %s\n", filename);
    lseek(ifile, 0x04, SEEK_SET);
    uint16_t offset;
    ssize_t rc = read(ifile, &offset, 2);
    EXIT_ON_ERR(rc != 2, "ERROR: Could not get 4 bytes. Only got %x\n", rc);
    lseek(ifile, offset, SEEK_SET);
    uint16_t file_version;
    rc = read(ifile, &file_version, 2);
    uint32_t file_version_low = (file_version >> 0) & 0xff;
    uint32_t file_version_high = (file_version >> 8) & 0xff;
    printf("File firmware version: %x.%x.%x.%x\n", file_version_high / 16, file_version_high % 16, file_version_low / 16, file_version_low % 16);
    close(ifile);
````

**Comment by cranphin** [comment]
This is what I get with a bit more debugging added, after unplugging and replugging the card first:
root@debian:~/upd72020x-load# make && ./upd72020x-miniload  -u -b 0x03 -d 0x00 -f 0x0 -i fwuPD7202xx.mem
make: Nothing to be done for 'all'.
Doing the upload
bus = 3 
dev = 0 
fct = 0 
fname = fwuPD7202xx.mem 
Found an UPD720202 chipset
Current firmware version: 2.0.1.1
File firmware version: 2.0.2.6
STATUS: enabling firmware upload
Old reg@0xf4: 0x0
Write reg@0xf4: 0x1
New reg@0xf4: 0x1
STATUS: performing firmware upload
ctrl_reg: 0xf4
databit: 0x8
Write value: 0x8ca755aa
databit: 0x9
Write value: 0xf60014
Old reg@0xf4: 0x1
Write reg@0xf4: 0x301
New reg@0xf4: 0x301
databit: 0x8
Write value: 0x4c010c
ERROR: SET_DATAx never go to zero
 ======> FAILED

More tomorrow :)

**Comment by cranphin** [comment]
My card is  btw. a cheap chinese ExpressCard 34mm.
It's made in 2011/10/12, it does has a flash chip (Puya P25D40H,  which gives id 00856013), which is preloaded with the 2.0.1.1 firmware.
The chip itself is a D720202 701 version

Looks like this:
![image](https://user-images.githubusercontent.com/234863/83349418-09b9ff00-a335-11ea-941c-7deb25e53022.png)

**Comment by cranphin** [comment]
Right, I guess it makes sense, but it seems the already loaded kernel driver was interfering in some way.
Doing this (command will depend on your exact setup) first seems to have made it work:
echo -n 0000:03:00.0 > /sys/bus/pci/drivers/xhci_hcd/unbind
After that and uploading the firmware it shows the new firmware version :)
To load the driver again I can use:
echo -n 0000:03:00.0 > /sys/bus/pci/drivers/xhci_hcd/bind
