### ISSUE TITLE
ERROR: ROM doesnt exist

### ISSUE THREAD

**Issue by GingKo-YOUTH** [markusj/upd72020x-load#9]
Hi，Markusj
When I customized the Nvidia TX2 carrier board, I used the upd720202 chip. The specific model is upd720202K8-711-BAA-A. As far as I know, this chip does not support external ROM uploading firmware, so the following error was reported when using your program. 

```
./upd72020x-load -u -b 0x01 -d 0x00 -f 0x0 -i K2013080.mem
Doing the upload
bus = 1 
dev = 0 
fct = 0 
fname = K2013080.mem 
Found an UPD720202 chipset
got firmware version: 200000
ERROR: ROM doesnt exist
no EEPROM installed
ERROR: cant open file image K2013080.mem
 ======> FAILED
```

Excuse me: 
1. Is it because your program can be used only when there is an external ROM? 
2. If yes, do you have a firmware downloading program that can provide it? 

Thank you very much ：)

**Comment by markusj** [comment]
Hi @GingKo-YOUTH 

>     1. Is it because your program can be used only when there is an external ROM?

No, the reported ERROR was misleading. The program still continued, but failed to open the firmware image file you provided. Please check the path you provided as argument:

> ```
> ERROR: cant open file image K2013080.mem
>  ======> FAILED
> ```

**Comment by GingKo-YOUTH** [comment]
Really appreciate
